export default {
  COLORS: {
    BACKGROUND: "#111111",
    BACKGROUND_LOGO: "#FFFFFF",
    BACKGROUND_IMAGE: "#2A2A2A",
    BACKGROUND_BORDER: "#3A3A3A",

    TEXT_PRIMARY: "#EEEEEE",
    TEXT_SECONDARY: "#B4B4B4",
  }
};