export default {
  COLORS: {
    BACKGROUND: "#FCFCFC",
    BACKGROUND_LOGO: "#FFFFFF",
    BACKGROUND_IMAGE: "#2A2A2A",
    BACKGROUND_BORDER: "#D9D9D9",

    TEXT_PRIMARY: "#202020",
    TEXT_SECONDARY: "#646464",
  }
};